name: myapp
description: "whathicke"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0' # Verifique sua versão do SDK

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

  timezone: ^0.9.2

  onesignal_flutter: ^5.0.0
  firebase_core: ^2.30.0 # Verifique a versão mais recente em pub.dev

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0